{
 "title": "Portworx Volume Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "px_cluster_cpu_percent" },
   {
    "name": "Volumes",
    "label": "Volume Name",
    "query": "px_volume_depth_io {cluster=\"[[Cluster]]\"}"
   }
  ]
 },
 "panels": [
  { "title": "All Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Read Latency (1m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_read_latency_seconds{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "Top n Volumes by Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk (10,(px_volume_usage_bytes{cluster=~\"[[Cluster]]\"}/px_volume_capacity_bytes{cluster=~\"[[Cluster]]\"})*100)",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top n Volumes by IO depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,px_volume_depth_io{cluster=\"[[Cluster]]\"})",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Avg Write Latency (1m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(px_volume_vol_write_latency_seconds{cluster=~\"[[Cluster]]\"})"
    }
   ]
  },
  {
   "title": "Replication Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "px_volume_replication_status{cluster=~\"[[Cluster]]\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume: [[Volumes]]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "Volumes",
   "collapsed": true,
   "panels": [
    {
     "title": "Current Replication Level (HA)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "px_volume_currhalevel{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{volumename}}",
       "measurement": "px_volume_halevel",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "I/O Priority",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "px_volume_iopriority{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{volumename}}",
       "measurement": "px_volume_halevel",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg Read Latency",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(px_volume_vol_read_latency_seconds{cluster=~\"[[Cluster]]\",volumename=~\"[[Volumes]]\"})"
      }
     ]
    },
    {
     "title": "Avg Write Latency",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(px_volume_vol_write_latency_seconds{cluster=~\"[[Cluster]]\",volumename=~\"[[Volumes]]\"})"
      }
     ]
    },
    {
     "title": "Volume Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Disk Capacity",
       "expr": "px_volume_capacity_bytes{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": " Capacity",
       "measurement": "px_volume_capacity_bytes",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Disk Usage",
       "expr": "px_volume_usage_bytes{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": " Usage",
       "measurement": "px_volume_usage_bytes",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Configured Replication Level (HA)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "px_volume_halevel{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{volumename}}",
       "measurement": "px_volume_halevel",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume total reads/writes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Bytes Written Throughput",
       "expr": "px_volume_num_long_reads{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "No. of  Reads ",
       "measurement": "px_volume_writethroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Bytes Read Throughput",
       "expr": "px_volume_num_long_writes{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "No. of  Writes ",
       "measurement": "px_volume_readthroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume IOPs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Bytes Written Throughput",
       "expr": "px_volume_iops{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "IOPs",
       "measurement": "px_volume_writethroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume Read/Written Bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Bytes Written Throughput",
       "expr": "px_volume_vol_read_bytes{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Bytes Read ",
       "measurement": "px_volume_writethroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Bytes Read Throughput",
       "expr": "px_volume_vol_written_bytes{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Bytes Written ",
       "measurement": "px_volume_readthroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "alias": "Read Latency",
       "expr": "px_volume_vol_read_latency_seconds{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "legendFormat": "Read Latency",
       "measurement": "px_volume_vol_read_latency_seconds",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Write Latency",
       "expr": "px_volume_vol_write_latency_seconds{volumename=~\"[[Volumes]]\"}\n",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "legendFormat": "Write Latency",
       "measurement": "px_volume_vol_write_latency_seconds",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume IO Depth",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "px_volume_depth_io{volumename=~\"[[Volumes]]\"}",
       "legendFormat": "I/O Depth"
      }
     ]
    },
    {
     "title": "Volume Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes Written Throughput",
       "expr": "px_volume_readthroughput{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Bytes Read Throughput",
       "measurement": "px_volume_writethroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Bytes Read Throughput",
       "expr": "px_volume_writethroughput{volumename=~\"[[Volumes]]\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Bytes Written Throughput",
       "measurement": "px_volume_readthroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Backup Status",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "px_backup_stats_status{volumename=~\"[[Volumes]]\"}"
      }
     ]
    },
    {
     "title": "Backup duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 4, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "px_backup_stats_duration_seconds{volumename=~\"[[Volumes]]\"}",
       "legendFormat": "{{volumename}}"
      }
     ]
    },
    {
     "title": "Backup Duration (Avg)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "px_backup_stats_duration_seconds{volumename=~\"[[Volumes]]\"}"
      }
     ]
    },
    {
     "title": "Backup Size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 4, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "px_backup_stats_size{volumename=~\"[[Volumes]]\"}",
       "legendFormat": "{{volumename}}"
      }
     ]
    },
    {
     "title": "Backup Size (Avg)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "px_backup_stats_size{volumename=~\"[[Volumes]]\"}"
      }
     ]
    }
   ]
  }
 ]
}