---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/x-forwarded-port: "443"
  name: portworx-ingress
  namespace: kube-system
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /grafana(/|$)(.*)
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: test